-- Pre-computed video recommendation rows.
-- Apply once against the application database, e.g.:
--   psql "$DATABASE_URL" -f scripts/sql/create-video-recommendation.sql

CREATE TABLE IF NOT EXISTS public.video_recommendation (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    video_id integer NOT NULL,
    recommended_video_id integer NOT NULL,
    rank integer NOT NULL,
    score double precision NOT NULL DEFAULT 0
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uq_video_recommendation_video_id_recommended_video_id'
    ) THEN
        ALTER TABLE public.video_recommendation
            ADD CONSTRAINT uq_video_recommendation_video_id_recommended_video_id
            UNIQUE (video_id, recommended_video_id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS ix_video_recommendation_video_id
    ON public.video_recommendation (video_id);

CREATE INDEX IF NOT EXISTS ix_video_recommendation_recommended_video_id
    ON public.video_recommendation (recommended_video_id);

CREATE INDEX IF NOT EXISTS ix_video_recommendation_video_id_rank
    ON public.video_recommendation (video_id, rank);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_video_recommendation_video_id_video'
    ) THEN
        ALTER TABLE public.video_recommendation
            ADD CONSTRAINT fk_video_recommendation_video_id_video
            FOREIGN KEY (video_id) REFERENCES public.video (id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_video_recommendation_recommended_video_id_video'
    ) THEN
        ALTER TABLE public.video_recommendation
            ADD CONSTRAINT fk_video_recommendation_recommended_video_id_video
            FOREIGN KEY (recommended_video_id) REFERENCES public.video (id) ON DELETE CASCADE;
    END IF;
END $$;
