"""add column email_verified column to table user

Revision ID: 22dc37a153e5
Revises: 8955082deb50
Create Date: 2026-09-29 14:59:06.176600

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '22dc37a153e5'
down_revision: Union[str, Sequence[str], None] = '8955082deb50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Make the email_verified column nullable initially
    op.add_column(
        'user',
        sa.Column(
            'email_verified',
            sa.Boolean(),
            nullable=True,
        ),
    )

    # Update existing rows to have email_verified set to False
    op.execute(
        "UPDATE \"user\" SET email_verified = FALSE WHERE email_verified IS NULL"
    )

    # Alter the column to be non-nullable after updating existing rows
    op.alter_column(
        'user',
        'email_verified',
        nullable=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        'user',
        'email_verified',
    )
    # ### end Alembic commands ###
