"""add refresh token

Revision ID: 5da6dd553a37
Revises: 2b37b88e11ba
Create Date: 2026-07-16 11:40:28.650115
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '5da6dd553a37'
down_revision: str | None = '2b37b88e11ba'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply forward migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('refresh_token_user_id_fkey'), 'refresh_token', type_='foreignkey')
    op.drop_constraint(op.f('refresh_token_replaced_by_id_fkey'), 'refresh_token', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_token', 'user', ['user_id'], ['id'], source_schema='app_user_schema', referent_schema='app_user_schema')
    op.create_foreign_key(None, 'refresh_token', 'refresh_token', ['replaced_by_id'], ['id'], source_schema='app_user_schema', referent_schema='app_user_schema')
    op.drop_constraint(op.f('user_credential_user_id_fkey'), 'user_credential', type_='foreignkey')
    op.create_foreign_key(None, 'user_credential', 'user', ['user_id'], ['id'], source_schema='app_user_schema', referent_schema='app_user_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_credential', schema='app_user_schema', type_='foreignkey')
    op.create_foreign_key(op.f('user_credential_user_id_fkey'), 'user_credential', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'refresh_token', schema='app_user_schema', type_='foreignkey')
    op.drop_constraint(None, 'refresh_token', schema='app_user_schema', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_token_replaced_by_id_fkey'), 'refresh_token', 'refresh_token', ['replaced_by_id'], ['id'])
    op.create_foreign_key(op.f('refresh_token_user_id_fkey'), 'refresh_token', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
