"""add column role to user

Revision ID: 6a37ff56fb06
Revises: b6ed5f1b79c2
Create Date: 2026-10-02 19:33:48.843078

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6a37ff56fb06'
down_revision: Union[str, Sequence[str], None] = 'b6ed5f1b79c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add the 'role' column to the 'user' table with nullable=True
    op.add_column(
        'user',
        sa.Column(
            'role',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )

    # Insert default value 'user' for existing rows
    op.execute("UPDATE \"user\" SET role = 'user' WHERE role IS NULL")

    # Alter the 'role' column to set nullable=False after populating existing rows
    op.alter_column('user', 'role', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
