"""add video_reaction and video_view

Revision ID: 783f5dc5439a
Revises: 1f6cb8db2a5b
Create Date: 2026-08-17 11:16:24.915804
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '783f5dc5439a'
down_revision: str | None = '1f6cb8db2a5b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply forward migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_comment_video_id_video'), 'comment', type_='foreignkey')
    op.drop_constraint(op.f('fk_comment_user_id_user'), 'comment', type_='foreignkey')
    op.create_foreign_key(op.f('fk_comment_video_id_video'), 'comment', 'video', ['video_id'], ['id'], source_schema='app_user_schema', referent_schema='public')
    op.create_foreign_key(op.f('fk_comment_user_id_user'), 'comment', 'user', ['user_id'], ['id'], source_schema='app_user_schema', referent_schema='app_user_schema')
    op.alter_column('playlist', 'visibility',
               existing_type=postgresql.ENUM('PUBLIC', 'PRIVATE', name='playlist_visibility'),
               type_=sa.Enum('PUBLIC', 'PRIVATE', name='playlist_visibility', schema='app_user_schema'),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_playlist_owner_id_user'), 'playlist', type_='foreignkey')
    op.create_foreign_key(op.f('fk_playlist_owner_id_user'), 'playlist', 'user', ['owner_id'], ['id'], source_schema='app_user_schema', referent_schema='app_user_schema')
    op.drop_constraint(op.f('fk_playlist_share_shared_with_user_id_user'), 'playlist_share', type_='foreignkey')
    op.drop_constraint(op.f('fk_playlist_share_playlist_id_playlist'), 'playlist_share', type_='foreignkey')
    op.create_foreign_key(op.f('fk_playlist_share_playlist_id_playlist'), 'playlist_share', 'playlist', ['playlist_id'], ['id'], source_schema='app_user_schema', referent_schema='app_user_schema')
    op.create_foreign_key(op.f('fk_playlist_share_shared_with_user_id_user'), 'playlist_share', 'user', ['shared_with_user_id'], ['id'], source_schema='app_user_schema', referent_schema='app_user_schema')
    op.drop_constraint(op.f('fk_playlist_video_video_id_video'), 'playlist_video', type_='foreignkey')
    op.drop_constraint(op.f('fk_playlist_video_playlist_id_playlist'), 'playlist_video', type_='foreignkey')
    op.create_foreign_key(op.f('fk_playlist_video_playlist_id_playlist'), 'playlist_video', 'playlist', ['playlist_id'], ['id'], source_schema='app_user_schema', referent_schema='app_user_schema')
    op.create_foreign_key(op.f('fk_playlist_video_video_id_video'), 'playlist_video', 'video', ['video_id'], ['id'], source_schema='app_user_schema', referent_schema='public')
    op.drop_constraint(op.f('fk_refresh_token_user_id_user'), 'refresh_token', type_='foreignkey')
    op.drop_constraint(op.f('fk_refresh_token_replaced_by_id_refresh_token'), 'refresh_token', type_='foreignkey')
    op.create_foreign_key(op.f('fk_refresh_token_user_id_user'), 'refresh_token', 'user', ['user_id'], ['id'], source_schema='app_user_schema', referent_schema='app_user_schema')
    op.create_foreign_key(op.f('fk_refresh_token_replaced_by_id_refresh_token'), 'refresh_token', 'refresh_token', ['replaced_by_id'], ['id'], source_schema='app_user_schema', referent_schema='app_user_schema')
    op.drop_constraint(op.f('fk_user_actress_subscribe_user_id_user'), 'user_actress_subscribe', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_actress_subscribe_actress_id_actress'), 'user_actress_subscribe', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_actress_subscribe_actress_id_actress'), 'user_actress_subscribe', 'actress', ['actress_id'], ['id'], source_schema='app_user_schema', referent_schema='public')
    op.create_foreign_key(op.f('fk_user_actress_subscribe_user_id_user'), 'user_actress_subscribe', 'user', ['user_id'], ['id'], source_schema='app_user_schema', referent_schema='app_user_schema')
    op.drop_constraint(op.f('fk_user_credential_user_id_user'), 'user_credential', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_credential_user_id_user'), 'user_credential', 'user', ['user_id'], ['id'], source_schema='app_user_schema', referent_schema='app_user_schema')
    op.drop_constraint(op.f('fk_video_reaction_video_id_video'), 'video_reaction', type_='foreignkey')
    op.drop_constraint(op.f('fk_video_reaction_user_id_user'), 'video_reaction', type_='foreignkey')
    op.create_foreign_key(op.f('fk_video_reaction_video_id_video'), 'video_reaction', 'video', ['video_id'], ['id'], source_schema='app_user_schema', referent_schema='public')
    op.create_foreign_key(op.f('fk_video_reaction_user_id_user'), 'video_reaction', 'user', ['user_id'], ['id'], source_schema='app_user_schema', referent_schema='app_user_schema')
    op.drop_constraint(op.f('fk_video_view_video_id_video'), 'video_view', type_='foreignkey')
    op.drop_constraint(op.f('fk_video_view_user_id_user'), 'video_view', type_='foreignkey')
    op.create_foreign_key(op.f('fk_video_view_user_id_user'), 'video_view', 'user', ['user_id'], ['id'], source_schema='app_user_schema', referent_schema='app_user_schema')
    op.create_foreign_key(op.f('fk_video_view_video_id_video'), 'video_view', 'video', ['video_id'], ['id'], source_schema='app_user_schema', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_video_view_video_id_video'), 'video_view', schema='app_user_schema', type_='foreignkey')
    op.drop_constraint(op.f('fk_video_view_user_id_user'), 'video_view', schema='app_user_schema', type_='foreignkey')
    op.create_foreign_key(op.f('fk_video_view_user_id_user'), 'video_view', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_video_view_video_id_video'), 'video_view', 'video', ['video_id'], ['id'])
    op.drop_constraint(op.f('fk_video_reaction_user_id_user'), 'video_reaction', schema='app_user_schema', type_='foreignkey')
    op.drop_constraint(op.f('fk_video_reaction_video_id_video'), 'video_reaction', schema='app_user_schema', type_='foreignkey')
    op.create_foreign_key(op.f('fk_video_reaction_user_id_user'), 'video_reaction', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_video_reaction_video_id_video'), 'video_reaction', 'video', ['video_id'], ['id'])
    op.drop_constraint(op.f('fk_user_credential_user_id_user'), 'user_credential', schema='app_user_schema', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_credential_user_id_user'), 'user_credential', 'user', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_user_actress_subscribe_user_id_user'), 'user_actress_subscribe', schema='app_user_schema', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_actress_subscribe_actress_id_actress'), 'user_actress_subscribe', schema='app_user_schema', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_actress_subscribe_actress_id_actress'), 'user_actress_subscribe', 'actress', ['actress_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_actress_subscribe_user_id_user'), 'user_actress_subscribe', 'user', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_refresh_token_replaced_by_id_refresh_token'), 'refresh_token', schema='app_user_schema', type_='foreignkey')
    op.drop_constraint(op.f('fk_refresh_token_user_id_user'), 'refresh_token', schema='app_user_schema', type_='foreignkey')
    op.create_foreign_key(op.f('fk_refresh_token_replaced_by_id_refresh_token'), 'refresh_token', 'refresh_token', ['replaced_by_id'], ['id'])
    op.create_foreign_key(op.f('fk_refresh_token_user_id_user'), 'refresh_token', 'user', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_playlist_video_video_id_video'), 'playlist_video', schema='app_user_schema', type_='foreignkey')
    op.drop_constraint(op.f('fk_playlist_video_playlist_id_playlist'), 'playlist_video', schema='app_user_schema', type_='foreignkey')
    op.create_foreign_key(op.f('fk_playlist_video_playlist_id_playlist'), 'playlist_video', 'playlist', ['playlist_id'], ['id'])
    op.create_foreign_key(op.f('fk_playlist_video_video_id_video'), 'playlist_video', 'video', ['video_id'], ['id'])
    op.drop_constraint(op.f('fk_playlist_share_shared_with_user_id_user'), 'playlist_share', schema='app_user_schema', type_='foreignkey')
    op.drop_constraint(op.f('fk_playlist_share_playlist_id_playlist'), 'playlist_share', schema='app_user_schema', type_='foreignkey')
    op.create_foreign_key(op.f('fk_playlist_share_playlist_id_playlist'), 'playlist_share', 'playlist', ['playlist_id'], ['id'])
    op.create_foreign_key(op.f('fk_playlist_share_shared_with_user_id_user'), 'playlist_share', 'user', ['shared_with_user_id'], ['id'])
    op.drop_constraint(op.f('fk_playlist_owner_id_user'), 'playlist', schema='app_user_schema', type_='foreignkey')
    op.create_foreign_key(op.f('fk_playlist_owner_id_user'), 'playlist', 'user', ['owner_id'], ['id'])
    op.alter_column('playlist', 'visibility',
               existing_type=sa.Enum('PUBLIC', 'PRIVATE', name='playlist_visibility', schema='app_user_schema'),
               type_=postgresql.ENUM('PUBLIC', 'PRIVATE', name='playlist_visibility'),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_comment_user_id_user'), 'comment', schema='app_user_schema', type_='foreignkey')
    op.drop_constraint(op.f('fk_comment_video_id_video'), 'comment', schema='app_user_schema', type_='foreignkey')
    op.create_foreign_key(op.f('fk_comment_user_id_user'), 'comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_comment_video_id_video'), 'comment', 'video', ['video_id'], ['id'])
    # ### end Alembic commands ###
