"""add video_recommendation

Revision ID: 8955082deb50
Revises: 9d0969a85524
Create Date: 2026-09-15 11:35:22.733378

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8955082deb50'
down_revision: Union[str, Sequence[str], None] = '9d0969a85524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'video_recommendation',
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('video_id', sa.Integer(), nullable=False),
        sa.Column('recommended_video_id', sa.Integer(), nullable=False),
        sa.Column('rank', sa.Integer(), nullable=False),
        sa.Column('score', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ['recommended_video_id'],
            ['public.video.id'],
            name=op.f('fk_video_recommendation_recommended_video_id_video'),
        ),
        sa.ForeignKeyConstraint(
            ['video_id'],
            ['public.video.id'],
            name=op.f('fk_video_recommendation_video_id_video'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_video_recommendation')),
        sa.UniqueConstraint(
            'video_id',
            'recommended_video_id',
            name=op.f('uq_video_recommendation_video_id'),
        ),
        schema='public',
    )
    op.create_index(
        op.f('ix_public_video_recommendation_recommended_video_id'),
        'video_recommendation',
        ['recommended_video_id'],
        unique=False,
        schema='public',
    )
    op.create_index(
        op.f('ix_public_video_recommendation_video_id'),
        'video_recommendation',
        ['video_id', 'rank'],
        unique=False,
        schema='public',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_public_video_recommendation_video_id'),
        table_name='video_recommendation',
        schema='public',
    )
    op.drop_index(
        op.f('ix_public_video_recommendation_recommended_video_id'),
        table_name='video_recommendation',
        schema='public',
    )
    op.drop_table('video_recommendation', schema='public')
    # ### end Alembic commands ###
