"""add watch events tables

Revision ID: 9a5b9296df8b
Revises: ddeaaccfad21
Create Date: 2026-10-05 09:33:03.430333

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9a5b9296df8b'
down_revision: Union[str, Sequence[str], None] = 'ddeaaccfad21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_watch_history',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column(
            'video_id',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'position_seconds',
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            'total_view_count',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'last_watched_at',
            sa.DateTime(),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['public.user.id'],
            name=op.f('fk_user_watch_history_user_id_user'),
        ),
        sa.ForeignKeyConstraint(
            ['video_id'],
            ['public.video.id'],
            name=op.f('fk_user_watch_history_video_id_video'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_user_watch_history')),
        sa.UniqueConstraint(
            'user_id',
            'video_id',
            name=op.f('uq_user_watch_history_user_id'),
        ),
        schema='public',
    )
    op.create_index(
        op.f('ix_public_user_watch_history_user_id'),
        'user_watch_history',
        ['user_id'],
        unique=False,
        schema='public',
    )
    op.create_index(
        op.f('ix_public_user_watch_history_video_id'),
        'user_watch_history',
        ['video_id'],
        unique=False,
        schema='public',
    )
    op.create_table(
        'watch_event',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column(
            'playback_session_id',
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column('user_id', sa.Uuid(), nullable=True),
        sa.Column(
            'video_id',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'event_type',
            sqlmodel.sql.sqltypes.AutoString(length=32),
            nullable=False,
        ),
        sa.Column(
            'position_seconds',
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            'is_eligible',
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['public.user.id'],
            name=op.f('fk_watch_event_user_id_user'),
        ),
        sa.ForeignKeyConstraint(
            ['video_id'],
            ['public.video.id'],
            name=op.f('fk_watch_event_video_id_video'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_watch_event')),
        schema='public',
    )
    op.create_index(
        op.f('ix_public_watch_event_event_type'),
        'watch_event',
        ['event_type'],
        unique=False,
        schema='public',
    )
    op.create_index(
        op.f('ix_public_watch_event_playback_session_id'),
        'watch_event',
        ['playback_session_id'],
        unique=False,
        schema='public',
    )
    op.create_index(
        op.f('ix_public_watch_event_user_id'),
        'watch_event',
        ['user_id'],
        unique=False,
        schema='public',
    )
    op.create_index(
        op.f('ix_public_watch_event_video_id'),
        'watch_event',
        ['video_id'],
        unique=False,
        schema='public',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_public_watch_event_video_id'),
        table_name='watch_event',
        schema='public',
    )
    op.drop_index(
        op.f('ix_public_watch_event_user_id'),
        table_name='watch_event',
        schema='public',
    )
    op.drop_index(
        op.f('ix_public_watch_event_playback_session_id'),
        table_name='watch_event',
        schema='public',
    )
    op.drop_index(
        op.f('ix_public_watch_event_event_type'),
        table_name='watch_event',
        schema='public',
    )
    op.drop_table('watch_event', schema='public')
    op.drop_index(
        op.f('ix_public_user_watch_history_video_id'),
        table_name='user_watch_history',
        schema='public',
    )
    op.drop_index(
        op.f('ix_public_user_watch_history_user_id'),
        table_name='user_watch_history',
        schema='public',
    )
    op.drop_table('user_watch_history', schema='public')
    # ### end Alembic commands ###
