"""add trigram indexes to video-related tables

Revision ID: 9d0969a85524
Revises: a6a2711d793e
Create Date: 2026-08-24 16:06:50.078105

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "9d0969a85524"
down_revision: Union[str, Sequence[str], None] = "a6a2711d793e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_public_director_name"),
        "director",
        [
            sa.literal_column("lower(name)").label("director_name_lower"),
        ],
        unique=False,
        schema="public",
        postgresql_ops={"director_name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_public_director_ruby"),
        "director",
        ["ruby"],
        unique=False,
        schema="public",
        postgresql_ops={"ruby": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_public_director_aka_translated_name"),
        "director_aka",
        [
            sa.literal_column("lower(translated_name)").label(
                "director_aka_translated_name_lower"
            )
        ],
        unique=False,
        schema="public",
        postgresql_ops={"director_aka_translated_name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_public_genre_name"),
        "genre",
        [
            sa.literal_column("lower(name)").label("genre_name_lower"),
        ],
        unique=False,
        schema="public",
        postgresql_ops={"genre_name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_public_genre_ruby"),
        "genre",
        ["ruby"],
        unique=False,
        schema="public",
        postgresql_ops={"ruby": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_public_genre_aka_translated_name"),
        "genre_aka",
        [
            sa.literal_column("lower(translated_name)").label(
                "genre_aka_translated_name_lower"
            )
        ],
        unique=False,
        schema="public",
        postgresql_ops={"genre_aka_translated_name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_public_label_name"),
        "label",
        [sa.literal_column("lower(name)").label("name_lower")],
        unique=False,
        schema="public",
        postgresql_ops={"name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_public_label_ruby"),
        "label",
        ["ruby"],
        unique=False,
        schema="public",
        postgresql_ops={"ruby": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_public_label_aka_translated_name"),
        "label_aka",
        [
            sa.literal_column("lower(translated_name)").label(
                "label_aka_translated_name_lower"
            )
        ],
        unique=False,
        schema="public",
        postgresql_ops={"label_aka_translated_name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_public_maker_name"),
        "maker",
        [
            sa.literal_column("lower(name)").label("maker_name_lower"),
        ],
        unique=False,
        schema="public",
        postgresql_ops={"maker_name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_public_maker_ruby"),
        "maker",
        ["ruby"],
        unique=False,
        schema="public",
        postgresql_ops={"ruby": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_public_maker_aka_translated_name"),
        "maker_aka",
        [
            sa.literal_column("lower(translated_name)").label(
                "maker_aka_translated_name_lower"
            )
        ],
        unique=False,
        schema="public",
        postgresql_ops={"maker_aka_translated_name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_public_series_name"),
        "series",
        [
            sa.literal_column("lower(name)").label("series_name_lower"),
        ],
        unique=False,
        schema="public",
        postgresql_ops={"series_name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_public_series_ruby"),
        "series",
        ["ruby"],
        unique=False,
        schema="public",
        postgresql_ops={"ruby": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_public_series_aka_translated_name"),
        "series_aka",
        [
            sa.literal_column("lower(translated_name)").label(
                "series_aka_translated_name_lower"
            )
        ],
        unique=False,
        schema="public",
        postgresql_ops={"series_aka_translated_name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_public_video_title"),
        "video",
        [
            sa.literal_column("lower(title)").label("video_title_lower"),
        ],
        unique=False,
        schema="public",
        postgresql_ops={"video_title_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_public_video_video_id_trgm"),
        "video",
        [
            sa.literal_column("lower(video_id)").label("video_video_id_lower"),
        ],
        unique=False,
        schema="public",
        postgresql_ops={"video_video_id_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_public_video_aka_translated_name"),
        "video_aka",
        [
            sa.literal_column("lower(translated_name)").label(
                "video_aka_translated_name_lower"
            )
        ],
        unique=False,
        schema="public",
        postgresql_ops={"video_aka_translated_name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_public_video_aka_translated_name"),
        table_name="video_aka",
        schema="public",
        postgresql_ops={"video_aka_translated_name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_public_video_video_id_trgm"),
        table_name="video",
        schema="public",
        postgresql_ops={"video_video_id_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_public_video_title"),
        table_name="video",
        schema="public",
        postgresql_ops={"video_title_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_public_series_aka_translated_name"),
        table_name="series_aka",
        schema="public",
        postgresql_ops={"series_aka_translated_name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_public_series_ruby"),
        table_name="series",
        schema="public",
        postgresql_ops={"ruby": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_public_series_name"),
        table_name="series",
        schema="public",
        postgresql_ops={"series_name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_public_maker_aka_translated_name"),
        table_name="maker_aka",
        schema="public",
        postgresql_ops={"maker_aka_translated_name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_public_maker_ruby"),
        table_name="maker",
        schema="public",
        postgresql_ops={"ruby": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_public_maker_name"),
        table_name="maker",
        schema="public",
        postgresql_ops={"maker_name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_public_label_aka_translated_name"),
        table_name="label_aka",
        schema="public",
        postgresql_ops={"label_aka_translated_name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_public_label_ruby"),
        table_name="label",
        schema="public",
        postgresql_ops={"ruby": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_public_label_name"),
        table_name="label",
        schema="public",
        postgresql_ops={"label_name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_public_genre_aka_translated_name"),
        table_name="genre_aka",
        schema="public",
        postgresql_ops={"genre_aka_translated_name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_public_genre_ruby"),
        table_name="genre",
        schema="public",
        postgresql_ops={"ruby": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_public_genre_name"),
        table_name="genre",
        schema="public",
        postgresql_ops={"genre_name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_public_director_aka_translated_name"),
        table_name="director_aka",
        schema="public",
        postgresql_ops={"director_aka_translated_name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_public_director_ruby"),
        table_name="director",
        schema="public",
        postgresql_ops={"ruby": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_public_director_name"),
        table_name="director",
        schema="public",
        postgresql_ops={"director_name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
