"""add trigram indexes to actress-related models

Revision ID: a6a2711d793e
Revises: 1c60ed83fb85
Create Date: 2026-08-24 09:42:01.812697

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "a6a2711d793e"
down_revision: Union[str, Sequence[str], None] = "1c60ed83fb85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_public_actress_name"),
        table_name="actress",
        postgresql_ops={"name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_public_actress_name"),
        "actress",
        [sa.literal_column("lower(name)").label("name_lower")],
        unique=False,
        schema="public",
        postgresql_ops={"name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_public_actress_ruby"),
        "actress",
        ["ruby"],
        unique=False,
        schema="public",
        postgresql_ops={"ruby": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_public_actress_aka_translated_name"),
        "actress_aka",
        [
            sa.literal_column("lower(translated_name)").label(
                "translated_name_lower"
            )
        ],
        unique=False,
        schema="public",
        postgresql_ops={"translated_name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_public_actress_aka_translated_name"),
        table_name="actress_aka",
        schema="public",
        postgresql_ops={"translated_name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_public_actress_ruby"),
        table_name="actress",
        schema="public",
        postgresql_ops={"ruby": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_public_actress_name"),
        table_name="actress",
        schema="public",
        postgresql_ops={"name_lower": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_public_actress_name"),
        "actress",
        ["name"],
        unique=False,
        postgresql_ops={"name": "gin_trgm_ops"},
        schema="public",
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
