"""add user_bio table

Revision ID: b6ed5f1b79c2
Revises: 22dc37a153e5
Create Date: 2026-10-02 16:54:54.613950

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b6ed5f1b79c2'
down_revision: Union[str, Sequence[str], None] = '22dc37a153e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_bio',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column(
            'full_name',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column(
            'date_of_birth',
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            'country',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column(
            'gender',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column(
            'biography',
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            'link',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['public.user.id'],
            name=op.f('fk_user_bio_user_id_user'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_user_bio')),
        schema='public',
    )
    op.create_index(
        op.f('ix_public_user_bio_user_id'),
        'user_bio',
        ['user_id'],
        unique=True,
        schema='public',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_public_user_bio_user_id'),
        table_name='user_bio',
        schema='public',
    )
    op.drop_table('user_bio', schema='public')
    # ### end Alembic commands ###
