"""add video_watch_progress table

Revision ID: ddeaaccfad21
Revises: 6a37ff56fb06
Create Date: 2026-10-05 08:51:07.522865

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ddeaaccfad21'
down_revision: Union[str, Sequence[str], None] = '6a37ff56fb06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('fk_video_view_video_id_video'),
        'video_view',
        type_='foreignkey',
    )
    op.drop_constraint(
        op.f('fk_video_view_user_id_user'),
        'video_view',
        type_='foreignkey',
    )
    op.create_foreign_key(
        op.f('fk_video_view_user_id_user'),
        'video_view',
        'user',
        ['user_id'],
        ['id'],
        source_schema='public',
        referent_schema='public',
    )
    op.create_foreign_key(
        op.f('fk_video_view_video_id_video'),
        'video_view',
        'video',
        ['video_id'],
        ['id'],
        source_schema='public',
        referent_schema='public',
    )
    op.drop_constraint(
        op.f('fk_video_watch_progress_user_id_user'),
        'video_watch_progress',
        type_='foreignkey',
    )
    op.drop_constraint(
        op.f('fk_video_watch_progress_video_id_video'),
        'video_watch_progress',
        type_='foreignkey',
    )
    op.create_foreign_key(
        op.f('fk_video_watch_progress_user_id_user'),
        'video_watch_progress',
        'user',
        ['user_id'],
        ['id'],
        source_schema='public',
        referent_schema='public',
    )
    op.create_foreign_key(
        op.f('fk_video_watch_progress_video_id_video'),
        'video_watch_progress',
        'video',
        ['video_id'],
        ['id'],
        source_schema='public',
        referent_schema='public',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('fk_video_watch_progress_video_id_video'),
        'video_watch_progress',
        schema='public',
        type_='foreignkey',
    )
    op.drop_constraint(
        op.f('fk_video_watch_progress_user_id_user'),
        'video_watch_progress',
        schema='public',
        type_='foreignkey',
    )
    op.create_foreign_key(
        op.f('fk_video_watch_progress_video_id_video'),
        'video_watch_progress',
        'video',
        ['video_id'],
        ['id'],
    )
    op.create_foreign_key(
        op.f('fk_video_watch_progress_user_id_user'),
        'video_watch_progress',
        'user',
        ['user_id'],
        ['id'],
    )
    op.drop_constraint(
        op.f('fk_video_view_video_id_video'),
        'video_view',
        schema='public',
        type_='foreignkey',
    )
    op.drop_constraint(
        op.f('fk_video_view_user_id_user'),
        'video_view',
        schema='public',
        type_='foreignkey',
    )
    op.create_foreign_key(
        op.f('fk_video_view_user_id_user'),
        'video_view',
        'user',
        ['user_id'],
        ['id'],
    )
    op.create_foreign_key(
        op.f('fk_video_view_video_id_video'),
        'video_view',
        'video',
        ['video_id'],
        ['id'],
    )
    # ### end Alembic commands ###
