"""add user-video comment models

Revision ID: f7b058e5a343
Revises: 5da6dd553a37
Create Date: 2026-07-16 14:15:13.459633
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f7b058e5a343"
down_revision: str | None = "5da6dd553a37"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply forward migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("fk_refresh_token_replaced_by_id_refresh_token"),
        "refresh_token",
        "refresh_token",
        ["replaced_by_id"],
        ["id"],
        source_schema="app_user_schema",
        referent_schema="app_user_schema",
    )
    op.create_foreign_key(
        op.f("fk_refresh_token_user_id_user"),
        "refresh_token",
        "user",
        ["user_id"],
        ["id"],
        source_schema="app_user_schema",
        referent_schema="app_user_schema",
    )
    op.create_foreign_key(
        op.f("fk_user_credential_user_id_user"),
        "user_credential",
        "user",
        ["user_id"],
        ["id"],
        source_schema="app_user_schema",
        referent_schema="app_user_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_credential_user_id_user"),
        "user_credential",
        schema="app_user_schema",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_refresh_token_user_id_user"),
        "refresh_token",
        schema="app_user_schema",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_refresh_token_replaced_by_id_refresh_token"),
        "refresh_token",
        schema="app_user_schema",
        type_="foreignkey",
    )
    # ### end Alembic commands ###
