/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as VideosRouteRouteImport } from './routes/videos/route'
import { Route as ActressesIndexRouteImport } from './routes/actresses/index'
import { Route as ActressesActressIdRouteImport } from './routes/actresses/$actressId'
import { Route as VideosIndexRouteImport } from './routes/videos/index'
import { Route as VideosIdRouteImport } from './routes/videos/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRouteRoute = VideosRouteRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ActressesIndexRoute = ActressesIndexRouteImport.update({
  id: '/actresses/',
  path: '/actresses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActressesActressIdRoute = ActressesActressIdRouteImport.update({
  id: '/actresses/$actressId',
  path: '/actresses/$actressId',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VideosRouteRoute,
} as any)
const VideosIdRoute = VideosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VideosRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/videos': typeof VideosRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/actresses/$actressId': typeof ActressesActressIdRoute
  '/videos/$id': typeof VideosIdRoute
  '/actresses/': typeof ActressesIndexRoute
  '/videos/': typeof VideosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/actresses/$actressId': typeof ActressesActressIdRoute
  '/videos/$id': typeof VideosIdRoute
  '/actresses': typeof ActressesIndexRoute
  '/videos': typeof VideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/videos': typeof VideosRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/actresses/$actressId': typeof ActressesActressIdRoute
  '/videos/$id': typeof VideosIdRoute
  '/actresses/': typeof ActressesIndexRoute
  '/videos/': typeof VideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/videos'
    | '/about'
    | '/register'
    | '/sign-in'
    | '/actresses/$actressId'
    | '/videos/$id'
    | '/actresses/'
    | '/videos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/register'
    | '/sign-in'
    | '/actresses/$actressId'
    | '/videos/$id'
    | '/actresses'
    | '/videos'
  id:
    | '__root__'
    | '/'
    | '/videos'
    | '/about'
    | '/register'
    | '/sign-in'
    | '/actresses/$actressId'
    | '/videos/$id'
    | '/actresses/'
    | '/videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VideosRouteRoute: typeof VideosRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  RegisterRoute: typeof RegisterRoute
  SignInRoute: typeof SignInRoute
  ActressesActressIdRoute: typeof ActressesActressIdRoute
  ActressesIndexRoute: typeof ActressesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actresses/': {
      id: '/actresses/'
      path: '/actresses'
      fullPath: '/actresses/'
      preLoaderRoute: typeof ActressesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actresses/$actressId': {
      id: '/actresses/$actressId'
      path: '/actresses/$actressId'
      fullPath: '/actresses/$actressId'
      preLoaderRoute: typeof ActressesActressIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof VideosRouteRoute
    }
    '/videos/$id': {
      id: '/videos/$id'
      path: '/$id'
      fullPath: '/videos/$id'
      preLoaderRoute: typeof VideosIdRouteImport
      parentRoute: typeof VideosRouteRoute
    }
  }
}

interface VideosRouteRouteChildren {
  VideosIdRoute: typeof VideosIdRoute
  VideosIndexRoute: typeof VideosIndexRoute
}

const VideosRouteRouteChildren: VideosRouteRouteChildren = {
  VideosIdRoute: VideosIdRoute,
  VideosIndexRoute: VideosIndexRoute,
}

const VideosRouteRouteWithChildren = VideosRouteRoute._addFileChildren(
  VideosRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VideosRouteRoute: VideosRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  RegisterRoute: RegisterRoute,
  SignInRoute: SignInRoute,
  ActressesActressIdRoute: ActressesActressIdRoute,
  ActressesIndexRoute: ActressesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
