/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as VideosRouteRouteImport } from './routes/videos/route'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as GuestForgotPasswordRouteImport } from './routes/_guest/forgot-password'
import { Route as GuestRegisterRouteImport } from './routes/_guest/register'
import { Route as GuestSignInRouteImport } from './routes/_guest/sign-in'
import { Route as ActressesIndexRouteImport } from './routes/actresses/index'
import { Route as ActressesActressIdRouteImport } from './routes/actresses/$actressId'
import { Route as UUsernameRouteRouteImport } from './routes/u/$username/route'
import { Route as VideosIndexRouteImport } from './routes/videos/index'
import { Route as VideosIdRouteImport } from './routes/videos/$id'
import { Route as UUsernameIndexRouteImport } from './routes/u/$username/index'
import { Route as UUsernameBlockedAccountsRouteImport } from './routes/u/$username/blocked-accounts'
import { Route as UUsernameContentPreferenceRouteImport } from './routes/u/$username/content-preference'
import { Route as UUsernameDeactivateRouteImport } from './routes/u/$username/deactivate'
import { Route as UUsernameNotificationsRouteImport } from './routes/u/$username/notifications'
import { Route as UUsernamePrivacyRouteImport } from './routes/u/$username/privacy'
import { Route as UUsernameSecurityRouteImport } from './routes/u/$username/security'
import { Route as UUsernameSubscriptionsRouteImport } from './routes/u/$username/subscriptions'
import { Route as UUsernameVideosRouteRouteImport } from './routes/u/$username/videos/route'
import { Route as UUsernameVideosIndexRouteImport } from './routes/u/$username/videos/index'
import { Route as UUsernameVideosHistoryRouteImport } from './routes/u/$username/videos/history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRouteRoute = VideosRouteRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const GuestForgotPasswordRoute = GuestForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => GuestRoute,
} as any)
const GuestRegisterRoute = GuestRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => GuestRoute,
} as any)
const GuestSignInRoute = GuestSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => GuestRoute,
} as any)
const ActressesIndexRoute = ActressesIndexRouteImport.update({
  id: '/actresses/',
  path: '/actresses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActressesActressIdRoute = ActressesActressIdRouteImport.update({
  id: '/actresses/$actressId',
  path: '/actresses/$actressId',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRouteRoute = UUsernameRouteRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VideosRouteRoute,
} as any)
const VideosIdRoute = VideosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VideosRouteRoute,
} as any)
const UUsernameIndexRoute = UUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UUsernameRouteRoute,
} as any)
const UUsernameBlockedAccountsRoute =
  UUsernameBlockedAccountsRouteImport.update({
    id: '/blocked-accounts',
    path: '/blocked-accounts',
    getParentRoute: () => UUsernameRouteRoute,
  } as any)
const UUsernameContentPreferenceRoute =
  UUsernameContentPreferenceRouteImport.update({
    id: '/content-preference',
    path: '/content-preference',
    getParentRoute: () => UUsernameRouteRoute,
  } as any)
const UUsernameDeactivateRoute = UUsernameDeactivateRouteImport.update({
  id: '/deactivate',
  path: '/deactivate',
  getParentRoute: () => UUsernameRouteRoute,
} as any)
const UUsernameNotificationsRoute = UUsernameNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => UUsernameRouteRoute,
} as any)
const UUsernamePrivacyRoute = UUsernamePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => UUsernameRouteRoute,
} as any)
const UUsernameSecurityRoute = UUsernameSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => UUsernameRouteRoute,
} as any)
const UUsernameSubscriptionsRoute = UUsernameSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => UUsernameRouteRoute,
} as any)
const UUsernameVideosRouteRoute = UUsernameVideosRouteRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => UUsernameRouteRoute,
} as any)
const UUsernameVideosIndexRoute = UUsernameVideosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UUsernameVideosRouteRoute,
} as any)
const UUsernameVideosHistoryRoute = UUsernameVideosHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => UUsernameVideosRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/videos': typeof VideosRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/u/$username': typeof UUsernameRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/register': typeof GuestRegisterRoute
  '/sign-in': typeof GuestSignInRoute
  '/actresses/$actressId': typeof ActressesActressIdRoute
  '/videos/$id': typeof VideosIdRoute
  '/actresses/': typeof ActressesIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/u/$username/videos': typeof UUsernameVideosRouteRouteWithChildren
  '/u/$username/blocked-accounts': typeof UUsernameBlockedAccountsRoute
  '/u/$username/content-preference': typeof UUsernameContentPreferenceRoute
  '/u/$username/deactivate': typeof UUsernameDeactivateRoute
  '/u/$username/notifications': typeof UUsernameNotificationsRoute
  '/u/$username/privacy': typeof UUsernamePrivacyRoute
  '/u/$username/security': typeof UUsernameSecurityRoute
  '/u/$username/subscriptions': typeof UUsernameSubscriptionsRoute
  '/u/$username/': typeof UUsernameIndexRoute
  '/u/$username/videos/history': typeof UUsernameVideosHistoryRoute
  '/u/$username/videos/': typeof UUsernameVideosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account': typeof AuthenticatedAccountRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/register': typeof GuestRegisterRoute
  '/sign-in': typeof GuestSignInRoute
  '/actresses/$actressId': typeof ActressesActressIdRoute
  '/videos/$id': typeof VideosIdRoute
  '/actresses': typeof ActressesIndexRoute
  '/videos': typeof VideosIndexRoute
  '/u/$username/blocked-accounts': typeof UUsernameBlockedAccountsRoute
  '/u/$username/content-preference': typeof UUsernameContentPreferenceRoute
  '/u/$username/deactivate': typeof UUsernameDeactivateRoute
  '/u/$username/notifications': typeof UUsernameNotificationsRoute
  '/u/$username/privacy': typeof UUsernamePrivacyRoute
  '/u/$username/security': typeof UUsernameSecurityRoute
  '/u/$username/subscriptions': typeof UUsernameSubscriptionsRoute
  '/u/$username': typeof UUsernameIndexRoute
  '/u/$username/videos/history': typeof UUsernameVideosHistoryRoute
  '/u/$username/videos': typeof UUsernameVideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/videos': typeof VideosRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/about': typeof AboutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/u/$username': typeof UUsernameRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_guest/forgot-password': typeof GuestForgotPasswordRoute
  '/_guest/register': typeof GuestRegisterRoute
  '/_guest/sign-in': typeof GuestSignInRoute
  '/actresses/$actressId': typeof ActressesActressIdRoute
  '/videos/$id': typeof VideosIdRoute
  '/actresses/': typeof ActressesIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/u/$username/videos': typeof UUsernameVideosRouteRouteWithChildren
  '/u/$username/blocked-accounts': typeof UUsernameBlockedAccountsRoute
  '/u/$username/content-preference': typeof UUsernameContentPreferenceRoute
  '/u/$username/deactivate': typeof UUsernameDeactivateRoute
  '/u/$username/notifications': typeof UUsernameNotificationsRoute
  '/u/$username/privacy': typeof UUsernamePrivacyRoute
  '/u/$username/security': typeof UUsernameSecurityRoute
  '/u/$username/subscriptions': typeof UUsernameSubscriptionsRoute
  '/u/$username/': typeof UUsernameIndexRoute
  '/u/$username/videos/history': typeof UUsernameVideosHistoryRoute
  '/u/$username/videos/': typeof UUsernameVideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/videos'
    | '/about'
    | '/reset-password'
    | '/verify-email'
    | '/u/$username'
    | '/account'
    | '/forgot-password'
    | '/register'
    | '/sign-in'
    | '/actresses/$actressId'
    | '/videos/$id'
    | '/actresses/'
    | '/videos/'
    | '/u/$username/videos'
    | '/u/$username/blocked-accounts'
    | '/u/$username/content-preference'
    | '/u/$username/deactivate'
    | '/u/$username/notifications'
    | '/u/$username/privacy'
    | '/u/$username/security'
    | '/u/$username/subscriptions'
    | '/u/$username/'
    | '/u/$username/videos/history'
    | '/u/$username/videos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/reset-password'
    | '/verify-email'
    | '/account'
    | '/forgot-password'
    | '/register'
    | '/sign-in'
    | '/actresses/$actressId'
    | '/videos/$id'
    | '/actresses'
    | '/videos'
    | '/u/$username/blocked-accounts'
    | '/u/$username/content-preference'
    | '/u/$username/deactivate'
    | '/u/$username/notifications'
    | '/u/$username/privacy'
    | '/u/$username/security'
    | '/u/$username/subscriptions'
    | '/u/$username'
    | '/u/$username/videos/history'
    | '/u/$username/videos'
  id:
    | '__root__'
    | '/'
    | '/videos'
    | '/_authenticated'
    | '/_guest'
    | '/about'
    | '/reset-password'
    | '/verify-email'
    | '/u/$username'
    | '/_authenticated/account'
    | '/_guest/forgot-password'
    | '/_guest/register'
    | '/_guest/sign-in'
    | '/actresses/$actressId'
    | '/videos/$id'
    | '/actresses/'
    | '/videos/'
    | '/u/$username/videos'
    | '/u/$username/blocked-accounts'
    | '/u/$username/content-preference'
    | '/u/$username/deactivate'
    | '/u/$username/notifications'
    | '/u/$username/privacy'
    | '/u/$username/security'
    | '/u/$username/subscriptions'
    | '/u/$username/'
    | '/u/$username/videos/history'
    | '/u/$username/videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VideosRouteRoute: typeof VideosRouteRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  AboutRoute: typeof AboutRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  UUsernameRouteRoute: typeof UUsernameRouteRouteWithChildren
  ActressesActressIdRoute: typeof ActressesActressIdRoute
  ActressesIndexRoute: typeof ActressesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_guest/forgot-password': {
      id: '/_guest/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof GuestForgotPasswordRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/register': {
      id: '/_guest/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof GuestRegisterRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/sign-in': {
      id: '/_guest/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof GuestSignInRouteImport
      parentRoute: typeof GuestRoute
    }
    '/actresses/': {
      id: '/actresses/'
      path: '/actresses'
      fullPath: '/actresses/'
      preLoaderRoute: typeof ActressesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actresses/$actressId': {
      id: '/actresses/$actressId'
      path: '/actresses/$actressId'
      fullPath: '/actresses/$actressId'
      preLoaderRoute: typeof ActressesActressIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof VideosRouteRoute
    }
    '/videos/$id': {
      id: '/videos/$id'
      path: '/$id'
      fullPath: '/videos/$id'
      preLoaderRoute: typeof VideosIdRouteImport
      parentRoute: typeof VideosRouteRoute
    }
    '/u/$username/': {
      id: '/u/$username/'
      path: '/'
      fullPath: '/u/$username/'
      preLoaderRoute: typeof UUsernameIndexRouteImport
      parentRoute: typeof UUsernameRouteRoute
    }
    '/u/$username/blocked-accounts': {
      id: '/u/$username/blocked-accounts'
      path: '/blocked-accounts'
      fullPath: '/u/$username/blocked-accounts'
      preLoaderRoute: typeof UUsernameBlockedAccountsRouteImport
      parentRoute: typeof UUsernameRouteRoute
    }
    '/u/$username/content-preference': {
      id: '/u/$username/content-preference'
      path: '/content-preference'
      fullPath: '/u/$username/content-preference'
      preLoaderRoute: typeof UUsernameContentPreferenceRouteImport
      parentRoute: typeof UUsernameRouteRoute
    }
    '/u/$username/deactivate': {
      id: '/u/$username/deactivate'
      path: '/deactivate'
      fullPath: '/u/$username/deactivate'
      preLoaderRoute: typeof UUsernameDeactivateRouteImport
      parentRoute: typeof UUsernameRouteRoute
    }
    '/u/$username/notifications': {
      id: '/u/$username/notifications'
      path: '/notifications'
      fullPath: '/u/$username/notifications'
      preLoaderRoute: typeof UUsernameNotificationsRouteImport
      parentRoute: typeof UUsernameRouteRoute
    }
    '/u/$username/privacy': {
      id: '/u/$username/privacy'
      path: '/privacy'
      fullPath: '/u/$username/privacy'
      preLoaderRoute: typeof UUsernamePrivacyRouteImport
      parentRoute: typeof UUsernameRouteRoute
    }
    '/u/$username/security': {
      id: '/u/$username/security'
      path: '/security'
      fullPath: '/u/$username/security'
      preLoaderRoute: typeof UUsernameSecurityRouteImport
      parentRoute: typeof UUsernameRouteRoute
    }
    '/u/$username/subscriptions': {
      id: '/u/$username/subscriptions'
      path: '/subscriptions'
      fullPath: '/u/$username/subscriptions'
      preLoaderRoute: typeof UUsernameSubscriptionsRouteImport
      parentRoute: typeof UUsernameRouteRoute
    }
    '/u/$username/videos': {
      id: '/u/$username/videos'
      path: '/videos'
      fullPath: '/u/$username/videos'
      preLoaderRoute: typeof UUsernameVideosRouteRouteImport
      parentRoute: typeof UUsernameRouteRoute
    }
    '/u/$username/videos/': {
      id: '/u/$username/videos/'
      path: '/'
      fullPath: '/u/$username/videos/'
      preLoaderRoute: typeof UUsernameVideosIndexRouteImport
      parentRoute: typeof UUsernameVideosRouteRoute
    }
    '/u/$username/videos/history': {
      id: '/u/$username/videos/history'
      path: '/history'
      fullPath: '/u/$username/videos/history'
      preLoaderRoute: typeof UUsernameVideosHistoryRouteImport
      parentRoute: typeof UUsernameVideosRouteRoute
    }
  }
}

interface VideosRouteRouteChildren {
  VideosIdRoute: typeof VideosIdRoute
  VideosIndexRoute: typeof VideosIndexRoute
}

const VideosRouteRouteChildren: VideosRouteRouteChildren = {
  VideosIdRoute: VideosIdRoute,
  VideosIndexRoute: VideosIndexRoute,
}

const VideosRouteRouteWithChildren = VideosRouteRoute._addFileChildren(
  VideosRouteRouteChildren,
)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface GuestRouteChildren {
  GuestForgotPasswordRoute: typeof GuestForgotPasswordRoute
  GuestRegisterRoute: typeof GuestRegisterRoute
  GuestSignInRoute: typeof GuestSignInRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestForgotPasswordRoute: GuestForgotPasswordRoute,
  GuestRegisterRoute: GuestRegisterRoute,
  GuestSignInRoute: GuestSignInRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

interface UUsernameVideosRouteRouteChildren {
  UUsernameVideosHistoryRoute: typeof UUsernameVideosHistoryRoute
  UUsernameVideosIndexRoute: typeof UUsernameVideosIndexRoute
}

const UUsernameVideosRouteRouteChildren: UUsernameVideosRouteRouteChildren = {
  UUsernameVideosHistoryRoute: UUsernameVideosHistoryRoute,
  UUsernameVideosIndexRoute: UUsernameVideosIndexRoute,
}

const UUsernameVideosRouteRouteWithChildren =
  UUsernameVideosRouteRoute._addFileChildren(UUsernameVideosRouteRouteChildren)

interface UUsernameRouteRouteChildren {
  UUsernameVideosRouteRoute: typeof UUsernameVideosRouteRouteWithChildren
  UUsernameBlockedAccountsRoute: typeof UUsernameBlockedAccountsRoute
  UUsernameContentPreferenceRoute: typeof UUsernameContentPreferenceRoute
  UUsernameDeactivateRoute: typeof UUsernameDeactivateRoute
  UUsernameNotificationsRoute: typeof UUsernameNotificationsRoute
  UUsernamePrivacyRoute: typeof UUsernamePrivacyRoute
  UUsernameSecurityRoute: typeof UUsernameSecurityRoute
  UUsernameSubscriptionsRoute: typeof UUsernameSubscriptionsRoute
  UUsernameIndexRoute: typeof UUsernameIndexRoute
}

const UUsernameRouteRouteChildren: UUsernameRouteRouteChildren = {
  UUsernameVideosRouteRoute: UUsernameVideosRouteRouteWithChildren,
  UUsernameBlockedAccountsRoute: UUsernameBlockedAccountsRoute,
  UUsernameContentPreferenceRoute: UUsernameContentPreferenceRoute,
  UUsernameDeactivateRoute: UUsernameDeactivateRoute,
  UUsernameNotificationsRoute: UUsernameNotificationsRoute,
  UUsernamePrivacyRoute: UUsernamePrivacyRoute,
  UUsernameSecurityRoute: UUsernameSecurityRoute,
  UUsernameSubscriptionsRoute: UUsernameSubscriptionsRoute,
  UUsernameIndexRoute: UUsernameIndexRoute,
}

const UUsernameRouteRouteWithChildren = UUsernameRouteRoute._addFileChildren(
  UUsernameRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VideosRouteRoute: VideosRouteRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  AboutRoute: AboutRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  UUsernameRouteRoute: UUsernameRouteRouteWithChildren,
  ActressesActressIdRoute: ActressesActressIdRoute,
  ActressesIndexRoute: ActressesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
