/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as VideosRouteRouteImport } from './routes/videos/route'
import { Route as ActressesIndexRouteImport } from './routes/actresses/index'
import { Route as ActressesActressIdRouteImport } from './routes/actresses/$actressId'
import { Route as GenresIndexRouteImport } from './routes/genres/index'
import { Route as GenresGenreRouteImport } from './routes/genres/$genre'
import { Route as VideosIndexRouteImport } from './routes/videos/index'
import { Route as VideosVideo_idRouteImport } from './routes/videos/$video_id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRouteRoute = VideosRouteRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ActressesIndexRoute = ActressesIndexRouteImport.update({
  id: '/actresses/',
  path: '/actresses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActressesActressIdRoute = ActressesActressIdRouteImport.update({
  id: '/actresses/$actressId',
  path: '/actresses/$actressId',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresIndexRoute = GenresIndexRouteImport.update({
  id: '/genres/',
  path: '/genres/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresGenreRoute = GenresGenreRouteImport.update({
  id: '/genres/$genre',
  path: '/genres/$genre',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VideosRouteRoute,
} as any)
const VideosVideo_idRoute = VideosVideo_idRouteImport.update({
  id: '/$video_id',
  path: '/$video_id',
  getParentRoute: () => VideosRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/videos': typeof VideosRouteRouteWithChildren
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/actresses/$actressId': typeof ActressesActressIdRoute
  '/genres/$genre': typeof GenresGenreRoute
  '/videos/$video_id': typeof VideosVideo_idRoute
  '/actresses/': typeof ActressesIndexRoute
  '/genres/': typeof GenresIndexRoute
  '/videos/': typeof VideosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/actresses/$actressId': typeof ActressesActressIdRoute
  '/genres/$genre': typeof GenresGenreRoute
  '/videos/$video_id': typeof VideosVideo_idRoute
  '/actresses': typeof ActressesIndexRoute
  '/genres': typeof GenresIndexRoute
  '/videos': typeof VideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/videos': typeof VideosRouteRouteWithChildren
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/actresses/$actressId': typeof ActressesActressIdRoute
  '/genres/$genre': typeof GenresGenreRoute
  '/videos/$video_id': typeof VideosVideo_idRoute
  '/actresses/': typeof ActressesIndexRoute
  '/genres/': typeof GenresIndexRoute
  '/videos/': typeof VideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/videos'
    | '/register'
    | '/sign-in'
    | '/actresses/$actressId'
    | '/genres/$genre'
    | '/videos/$video_id'
    | '/actresses/'
    | '/genres/'
    | '/videos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/sign-in'
    | '/actresses/$actressId'
    | '/genres/$genre'
    | '/videos/$video_id'
    | '/actresses'
    | '/genres'
    | '/videos'
  id:
    | '__root__'
    | '/'
    | '/videos'
    | '/register'
    | '/sign-in'
    | '/actresses/$actressId'
    | '/genres/$genre'
    | '/videos/$video_id'
    | '/actresses/'
    | '/genres/'
    | '/videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VideosRouteRoute: typeof VideosRouteRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  SignInRoute: typeof SignInRoute
  ActressesActressIdRoute: typeof ActressesActressIdRoute
  GenresGenreRoute: typeof GenresGenreRoute
  ActressesIndexRoute: typeof ActressesIndexRoute
  GenresIndexRoute: typeof GenresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actresses/': {
      id: '/actresses/'
      path: '/actresses'
      fullPath: '/actresses/'
      preLoaderRoute: typeof ActressesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actresses/$actressId': {
      id: '/actresses/$actressId'
      path: '/actresses/$actressId'
      fullPath: '/actresses/$actressId'
      preLoaderRoute: typeof ActressesActressIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres/': {
      id: '/genres/'
      path: '/genres'
      fullPath: '/genres/'
      preLoaderRoute: typeof GenresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres/$genre': {
      id: '/genres/$genre'
      path: '/genres/$genre'
      fullPath: '/genres/$genre'
      preLoaderRoute: typeof GenresGenreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof VideosRouteRoute
    }
    '/videos/$video_id': {
      id: '/videos/$video_id'
      path: '/$video_id'
      fullPath: '/videos/$video_id'
      preLoaderRoute: typeof VideosVideo_idRouteImport
      parentRoute: typeof VideosRouteRoute
    }
  }
}

interface VideosRouteRouteChildren {
  VideosVideo_idRoute: typeof VideosVideo_idRoute
  VideosIndexRoute: typeof VideosIndexRoute
}

const VideosRouteRouteChildren: VideosRouteRouteChildren = {
  VideosVideo_idRoute: VideosVideo_idRoute,
  VideosIndexRoute: VideosIndexRoute,
}

const VideosRouteRouteWithChildren = VideosRouteRoute._addFileChildren(
  VideosRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VideosRouteRoute: VideosRouteRouteWithChildren,
  RegisterRoute: RegisterRoute,
  SignInRoute: SignInRoute,
  ActressesActressIdRoute: ActressesActressIdRoute,
  GenresGenreRoute: GenresGenreRoute,
  ActressesIndexRoute: ActressesIndexRoute,
  GenresIndexRoute: GenresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
