"""add login credentials table

Revision ID: 2b37b88e11ba
Revises: fc041c5a545c
Create Date: 2026-07-15 19:58:23.092885
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "2b37b88e11ba"
down_revision: str | None = "fc041c5a545c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply forward migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="app_user_schema",
    )
    op.create_index(
        op.f("ix_app_user_schema_user_email"),
        "user",
        ["email"],
        unique=True,
        schema="app_user_schema",
    )
    op.create_index(
        op.f("ix_app_user_schema_user_username"),
        "user",
        ["username"],
        unique=True,
        schema="app_user_schema",
    )
    op.create_table(
        "refresh_token",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "issued_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("replaced_by_id", sa.Uuid(), nullable=True),
        sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("ip_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["app_user_schema.refresh_token.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user_schema.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="app_user_schema",
    )
    op.create_index(
        op.f("ix_app_user_schema_refresh_token_token_hash"),
        "refresh_token",
        ["token_hash"],
        unique=True,
        schema="app_user_schema",
    )
    op.create_index(
        op.f("ix_app_user_schema_refresh_token_user_id"),
        "refresh_token",
        ["user_id"],
        unique=False,
        schema="app_user_schema",
    )
    op.create_table(
        "user_credential",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "password_algorithm", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("password_changed_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user_schema.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="app_user_schema",
    )
    op.create_index(
        op.f("ix_app_user_schema_user_credential_user_id"),
        "user_credential",
        ["user_id"],
        unique=True,
        schema="app_user_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_app_user_schema_user_credential_user_id"),
        table_name="user_credential",
        schema="app_user_schema",
    )
    op.drop_table("user_credential", schema="app_user_schema")
    op.drop_index(
        op.f("ix_app_user_schema_refresh_token_user_id"),
        table_name="refresh_token",
        schema="app_user_schema",
    )
    op.drop_index(
        op.f("ix_app_user_schema_refresh_token_token_hash"),
        table_name="refresh_token",
        schema="app_user_schema",
    )
    op.drop_table("refresh_token", schema="app_user_schema")
    op.drop_index(
        op.f("ix_app_user_schema_user_username"),
        table_name="user",
        schema="app_user_schema",
    )
    op.drop_index(
        op.f("ix_app_user_schema_user_email"),
        table_name="user",
        schema="app_user_schema",
    )
    op.drop_table("user", schema="app_user_schema")
    # ### end Alembic commands ###
