"""add user-video like  models

Revision ID: 61611372fb32
Revises: d4ec0a2da992
Create Date: 2026-07-16 15:40:07.294577
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "61611372fb32"
down_revision: str | None = "d4ec0a2da992"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply forward migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "video_like",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "video_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user_schema.user.id"],
            name=op.f("fk_video_like_user_id_user"),
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["public.video.id"],
            name=op.f("fk_video_like_video_id_video"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video_like")),
        sa.UniqueConstraint(
            "user_id",
            "video_id",
            name="uq_video_like_user_video",
        ),
        schema="app_user_schema",
    )
    op.create_index(
        op.f("ix_app_user_schema_video_like_user_id"),
        "video_like",
        ["user_id"],
        unique=False,
        schema="app_user_schema",
    )
    op.create_index(
        op.f("ix_app_user_schema_video_like_video_id"),
        "video_like",
        ["video_id"],
        unique=False,
        schema="app_user_schema",
    )
    op.drop_constraint(
        op.f("fk_comment_user_id_user"),
        "comment",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_comment_video_id_video"),
        "comment",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_comment_user_id_user"),
        "comment",
        "user",
        ["user_id"],
        ["id"],
        source_schema="app_user_schema",
        referent_schema="app_user_schema",
    )
    op.create_foreign_key(
        op.f("fk_comment_video_id_video"),
        "comment",
        "video",
        ["video_id"],
        ["id"],
        source_schema="app_user_schema",
        referent_schema="public",
    )
    op.drop_constraint(
        op.f(
            "fk_refresh_token_replaced_by_id_refresh_token",
        ),
        "refresh_token",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_refresh_token_user_id_user"),
        "refresh_token",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f(
            "fk_refresh_token_replaced_by_id_refresh_token",
        ),
        "refresh_token",
        "refresh_token",
        ["replaced_by_id"],
        ["id"],
        source_schema="app_user_schema",
        referent_schema="app_user_schema",
    )
    op.create_foreign_key(
        op.f("fk_refresh_token_user_id_user"),
        "refresh_token",
        "user",
        ["user_id"],
        ["id"],
        source_schema="app_user_schema",
        referent_schema="app_user_schema",
    )
    op.drop_constraint(
        op.f("fk_user_credential_user_id_user"),
        "user_credential",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_user_credential_user_id_user"),
        "user_credential",
        "user",
        ["user_id"],
        ["id"],
        source_schema="app_user_schema",
        referent_schema="app_user_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_credential_user_id_user"),
        "user_credential",
        schema="app_user_schema",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_user_credential_user_id_user"),
        "user_credential",
        "user",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_refresh_token_user_id_user"),
        "refresh_token",
        schema="app_user_schema",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f(
            "fk_refresh_token_replaced_by_id_refresh_token",
        ),
        "refresh_token",
        schema="app_user_schema",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_refresh_token_user_id_user"),
        "refresh_token",
        "user",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f(
            "fk_refresh_token_replaced_by_id_refresh_token",
        ),
        "refresh_token",
        "refresh_token",
        ["replaced_by_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_comment_video_id_video"),
        "comment",
        schema="app_user_schema",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_comment_user_id_user"),
        "comment",
        schema="app_user_schema",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_comment_video_id_video"),
        "comment",
        "video",
        ["video_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_comment_user_id_user"),
        "comment",
        "user",
        ["user_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_app_user_schema_video_like_video_id"),
        table_name="video_like",
        schema="app_user_schema",
    )
    op.drop_index(
        op.f("ix_app_user_schema_video_like_user_id"),
        table_name="video_like",
        schema="app_user_schema",
    )
    op.drop_table("video_like", schema="app_user_schema")
    # ### end Alembic commands ###
