"""add playlist  models

Revision ID: 8f8effefb51e
Revises: 61611372fb32
Create Date: 2026-07-16 16:17:50.462693
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "8f8effefb51e"
down_revision: str | None = "61611372fb32"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

playlist_visibility_enum = postgresql.ENUM(
    "PUBLIC",
    "PRIVATE",
    name="playlist_visibility",
    schema="app_user_schema",
)


def upgrade() -> None:
    """Apply forward migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlist",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column(
            "name",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column(
            "description",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column(
            "visibility",
            playlist_visibility_enum,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["app_user_schema.user.id"],
            name=op.f("fk_playlist_owner_id_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_playlist")),
        schema="app_user_schema",
    )
    op.create_index(
        op.f("ix_app_user_schema_playlist_owner_id"),
        "playlist",
        ["owner_id"],
        unique=False,
        schema="app_user_schema",
    )
    op.create_table(
        "playlist_share",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "playlist_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "shared_with_user_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "can_edit",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["app_user_schema.playlist.id"],
            name=op.f("fk_playlist_share_playlist_id_playlist"),
        ),
        sa.ForeignKeyConstraint(
            ["shared_with_user_id"],
            ["app_user_schema.user.id"],
            name=op.f("fk_playlist_share_shared_with_user_id_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_playlist_share")),
        sa.UniqueConstraint(
            "playlist_id",
            "shared_with_user_id",
            name="uq_playlist_share_playlist_user",
        ),
        schema="app_user_schema",
    )
    op.create_index(
        op.f("ix_app_user_schema_playlist_share_playlist_id"),
        "playlist_share",
        ["playlist_id"],
        unique=False,
        schema="app_user_schema",
    )
    op.create_index(
        op.f(
            "ix_app_user_schema_playlist_share_shared_with_user_id",
        ),
        "playlist_share",
        ["shared_with_user_id"],
        unique=False,
        schema="app_user_schema",
    )
    op.create_table(
        "playlist_video",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "playlist_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "video_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "position",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "added_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["app_user_schema.playlist.id"],
            name=op.f("fk_playlist_video_playlist_id_playlist"),
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["public.video.id"],
            name=op.f("fk_playlist_video_video_id_video"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_playlist_video")),
        sa.UniqueConstraint(
            "playlist_id",
            "video_id",
            name="uq_playlist_video_playlist_video",
        ),
        schema="app_user_schema",
    )
    op.create_index(
        op.f("ix_app_user_schema_playlist_video_playlist_id"),
        "playlist_video",
        ["playlist_id"],
        unique=False,
        schema="app_user_schema",
    )
    op.create_index(
        op.f("ix_app_user_schema_playlist_video_video_id"),
        "playlist_video",
        ["video_id"],
        unique=False,
        schema="app_user_schema",
    )
    op.drop_constraint(
        op.f("fk_comment_video_id_video"),
        "comment",
        type_="foreignkey",
        schema="app_user_schema",
    )
    op.drop_constraint(
        op.f("fk_comment_user_id_user"),
        "comment",
        type_="foreignkey",
        schema="app_user_schema",
    )
    op.create_foreign_key(
        op.f("fk_comment_video_id_video"),
        "comment",
        "video",
        ["video_id"],
        ["id"],
        source_schema="app_user_schema",
        referent_schema="public",
    )
    op.create_foreign_key(
        op.f("fk_comment_user_id_user"),
        "comment",
        "user",
        ["user_id"],
        ["id"],
        source_schema="app_user_schema",
        referent_schema="app_user_schema",
    )
    op.drop_constraint(
        op.f("fk_refresh_token_user_id_user"),
        "refresh_token",
        type_="foreignkey",
        schema="app_user_schema",
    )
    op.drop_constraint(
        op.f("fk_refresh_token_replaced_by_id_refresh_token"),
        "refresh_token",
        type_="foreignkey",
        schema="app_user_schema",
    )
    op.create_foreign_key(
        op.f("fk_refresh_token_user_id_user"),
        "refresh_token",
        "user",
        ["user_id"],
        ["id"],
        source_schema="app_user_schema",
        referent_schema="app_user_schema",
    )
    op.create_foreign_key(
        op.f("fk_refresh_token_replaced_by_id_refresh_token"),
        "refresh_token",
        "refresh_token",
        ["replaced_by_id"],
        ["id"],
        source_schema="app_user_schema",
        referent_schema="app_user_schema",
    )
    op.drop_constraint(
        op.f("fk_user_credential_user_id_user"), "user_credential", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_user_credential_user_id_user"),
        "user_credential",
        "user",
        ["user_id"],
        ["id"],
        source_schema="app_user_schema",
        referent_schema="app_user_schema",
    )
    op.drop_constraint(
        op.f("fk_video_like_video_id_video"), "video_like", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_video_like_user_id_user"), "video_like", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_video_like_video_id_video"),
        "video_like",
        "video",
        ["video_id"],
        ["id"],
        source_schema="app_user_schema",
        referent_schema="public",
    )
    op.create_foreign_key(
        op.f("fk_video_like_user_id_user"),
        "video_like",
        "user",
        ["user_id"],
        ["id"],
        source_schema="app_user_schema",
        referent_schema="app_user_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_video_like_user_id_user"),
        "video_like",
        schema="app_user_schema",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_video_like_video_id_video"),
        "video_like",
        schema="app_user_schema",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_video_like_user_id_user"),
        "video_like",
        "user",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_video_like_video_id_video"),
        "video_like",
        "video",
        ["video_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_user_credential_user_id_user"),
        "user_credential",
        schema="app_user_schema",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_user_credential_user_id_user"),
        "user_credential",
        "user",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_refresh_token_replaced_by_id_refresh_token"),
        "refresh_token",
        schema="app_user_schema",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_refresh_token_user_id_user"),
        "refresh_token",
        schema="app_user_schema",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_refresh_token_replaced_by_id_refresh_token"),
        "refresh_token",
        "refresh_token",
        ["replaced_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_refresh_token_user_id_user"),
        "refresh_token",
        "user",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_comment_user_id_user"),
        "comment",
        schema="app_user_schema",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_comment_video_id_video"),
        "comment",
        schema="app_user_schema",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_comment_user_id_user"),
        "comment",
        "user",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_comment_video_id_video"),
        "comment",
        "video",
        ["video_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_app_user_schema_playlist_video_video_id"),
        table_name="playlist_video",
        schema="app_user_schema",
    )
    op.drop_index(
        op.f("ix_app_user_schema_playlist_video_playlist_id"),
        table_name="playlist_video",
        schema="app_user_schema",
    )
    op.drop_table("playlist_video", schema="app_user_schema")
    op.drop_index(
        op.f("ix_app_user_schema_playlist_share_shared_with_user_id"),
        table_name="playlist_share",
        schema="app_user_schema",
    )
    op.drop_index(
        op.f("ix_app_user_schema_playlist_share_playlist_id"),
        table_name="playlist_share",
        schema="app_user_schema",
    )
    op.drop_table("playlist_share", schema="app_user_schema")
    op.drop_index(
        op.f("ix_app_user_schema_playlist_owner_id"),
        table_name="playlist",
        schema="app_user_schema",
    )
    op.drop_table("playlist", schema="app_user_schema")
    playlist_visibility_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
